
#!/usr/bin/env python3
"""
DIMENSION 7 SCORER V2.0 - PHASE 1A
Investment OS - Market Sentiment Enhancement

FILE: dimension7_scorer_v2_0_phase1a.py
CREATED: 2026-01-07
AUTHOR: Investment OS

VERSION HISTORY:
    v2.0.0-1a  2026-01-07  Initial creation — Phase 1A scorer (3 components: Activity, Volatility, Recognition)
    v2.0.1-1a  2026-02-10  Migrated to services/scoring-7d (Phase 2 microservices)
    v2.0.2-1a  2026-02-16  Added version history header (new project standard)

Phase 1, Day 3: Parallel Scoring Implementation

PURPOSE:
Enhanced market sentiment scoring using real CSE exchange data.
Runs in parallel with v1.0 for validation before migration.

PHASE 1A CAPABILITIES (Jan 2026):
✅ Component 1: Trading Activity (40%) - ENHANCED with CSE data
✅ Component 2: Volatility Adjustment (10%) - NEW
✅ Component 3: Market Recognition (50%) - From v1.0

UNAVAILABLE (Need History):
⏳ Component 4: Volume Trends (need 20D data - Feb 3)
⏳ Component 5: Multi-Timeframe Momentum (need 5D/20D/60D - Feb-Apr)

SCORING METHODOLOGY:
- Uses empirical CSE percentiles (no arbitrary thresholds)
- Trade Volume + Share Volume = Activity score
- Trade Density = Institutional detection (informational)
- Intraday Volatility = Fair comparison adjustment
- Market Recognition = From v1.0 (analyst data)

PARALLEL DEPLOYMENT:
- Runs alongside v1.0 (production unchanged)
- Separate output: dimension7_v2_scores.csv
- Enables validation and comparison

VERSION: 2.0-phase1a
DATE: January 7, 2026
AUTHOR: Investment OS Team
"""

import pandas as pd
import numpy as np
import json
from datetime import datetime
from typing import Dict, Optional
import argparse
import sys

# =============================================================================
# CONFIGURATION
# =============================================================================

# Percentiles file (generated by cse_percentile_calculator.py)
PERCENTILES_FILE = 'cse_percentiles.json'

# Component weights (Phase 1A)
WEIGHTS = {
    'trading_activity': 0.40,      # Enhanced with CSE data
    'volatility_adjustment': 0.10,  # New - fair comparison
    'market_recognition': 0.50      # From v1.0
}

# =============================================================================
# LOAD PERCENTILES
# =============================================================================

def load_percentiles(filepath: str = PERCENTILES_FILE) -> Dict:
    """
    Load CSE percentile thresholds.
    
    Args:
        filepath: Path to percentiles JSON
    
    Returns:
        Dictionary with percentile data
    """
    try:
        with open(filepath, 'r') as f:
            percentiles = json.load(f)
        
        print(f"✅ Loaded percentiles: {filepath}")
        print(f"   Generated: {percentiles['generated_at']}")
        print(f"   Stocks: {percentiles['stocks_analyzed']}")
        
        return percentiles
    
    except FileNotFoundError:
        print(f"❌ ERROR: Percentiles file not found: {filepath}")
        print("   Run: python3 cse_percentile_calculator.py cse_metrics.csv")
        sys.exit(1)
    except Exception as e:
        print(f"❌ ERROR loading percentiles: {e}")
        sys.exit(1)

# =============================================================================
# SCORING FUNCTIONS
# =============================================================================

def score_by_percentile(value: float, bands: Dict, direction: str = 'higher_better') -> float:
    """
    Score a value using percentile bands.
    
    Args:
        value: Value to score
        bands: Scoring bands from percentiles
        direction: 'higher_better' or 'lower_better'
    
    Returns:
        Score (0-100)
    """
    if pd.isna(value):
        return 50.0  # Neutral score for missing data
    
    # Get band thresholds
    if direction == 'higher_better':
        if value >= bands['exceptional']['min']:
            # Exceptional: 90-100 (linear interpolation within band)
            return 95.0  # Simplified: mid-range of 90-100
        elif value >= bands['strong']['min']:
            # Strong: 75-89
            return 82.0
        elif value >= bands['moderate']['min']:
            # Moderate: 50-74
            return 62.0
        elif value >= bands['weak']['min']:
            # Weak: 25-49
            return 37.0
        else:
            # Poor: 0-24
            return 12.0
    
    elif direction == 'lower_better':
        if value <= bands['exceptional']['max']:
            return 95.0
        elif value <= bands['strong']['max']:
            return 82.0
        elif value <= bands['moderate']['max']:
            return 62.0
        elif value <= bands['weak']['max']:
            return 37.0
        else:
            return 12.0
    
    return 50.0  # Default neutral

def calculate_trading_activity(row: pd.Series, percentiles: Dict) -> Dict:
    """
    Component 1: Trading Activity (40% weight)
    
    Uses:
    - Trade Volume (50% of component)
    - Share Volume (50% of component)
    - Trade Density (informational - not scored directly)
    
    Args:
        row: Stock data row
        percentiles: Percentile thresholds
    
    Returns:
        Dictionary with component scores and details
    """
    # Get percentile bands
    tv_bands = percentiles['metrics']['trade_volume']['scoring_bands']
    sv_bands = percentiles['metrics']['share_volume']['scoring_bands']
    
    # Score trade volume
    trade_volume_score = score_by_percentile(
        row['trade_volume'], 
        tv_bands, 
        'higher_better'
    )
    
    # Score share volume
    share_volume_score = score_by_percentile(
        row['share_volume'], 
        sv_bands, 
        'higher_better'
    )
    
    # Combined activity score (50/50 weight)
    activity_score = (trade_volume_score * 0.5) + (share_volume_score * 0.5)
    
    # Trade density classification (informational)
    trade_density = row['trade_density']
    if pd.notna(trade_density):
        if trade_density >= 10000:
            density_class = 'institutional'
        elif trade_density >= 1000:
            density_class = 'mixed'
        else:
            density_class = 'retail'
    else:
        density_class = 'unknown'
    
    return {
        'component_score': activity_score,
        'trade_volume_score': trade_volume_score,
        'share_volume_score': share_volume_score,
        'trade_density_class': density_class
    }

def calculate_volatility_adjustment(row: pd.Series, percentiles: Dict) -> Dict:
    """
    Component 2: Volatility Adjustment (10% weight)
    
    Purpose: Fair comparison across volatility profiles
    - Very stable stocks (low vol): Slight bonus
    - Very volatile stocks (high vol): Slight penalty
    - Most stocks: Neutral
    
    Args:
        row: Stock data row
        percentiles: Percentile thresholds
    
    Returns:
        Dictionary with adjustment score
    """
    volatility = row['intraday_volatility']
    
    if pd.isna(volatility):
        return {'component_score': 50.0, 'volatility_level': 'unknown'}
    
    # Get percentile bands
    vol_bands = percentiles['metrics']['intraday_volatility']['scoring_bands']
    
    # Classification
    if volatility >= vol_bands['very_high']['min']:
        # Very volatile: 40 (penalty)
        return {'component_score': 40.0, 'volatility_level': 'very_high'}
    elif volatility >= vol_bands['high']['min']:
        # High volatility: 45 (slight penalty)
        return {'component_score': 45.0, 'volatility_level': 'high'}
    elif volatility <= vol_bands['very_low']['max']:
        # Very stable: 60 (bonus)
        return {'component_score': 60.0, 'volatility_level': 'very_low'}
    elif volatility <= vol_bands['low']['max']:
        # Stable: 55 (slight bonus)
        return {'component_score': 55.0, 'volatility_level': 'low'}
    else:
        # Moderate: 50 (neutral)
        return {'component_score': 50.0, 'volatility_level': 'moderate'}

def calculate_market_recognition(row: pd.Series) -> Dict:
    """
    Component 3: Market Recognition (50% weight)
    
    Uses v1.0 methodology (StockAnalysis.com data):
    - Analyst recommendations
    - Total return metrics
    
    Note: This component remains unchanged from v1.0 for Phase 1A
    Will be enhanced in future phases with more CSE data
    
    Args:
        row: Stock data row
    
    Returns:
        Dictionary with component score
    """
    # Placeholder: Use analyst_score if available
    # Otherwise neutral score
    
    if 'analyst_score' in row.index and pd.notna(row['analyst_score']):
        score = row['analyst_score']
    else:
        # Default neutral score if no analyst data
        score = 50.0
    
    return {
        'component_score': score,
        'data_source': 'v1.0_analyst_data'
    }

# =============================================================================
# COMPOSITE SCORING
# =============================================================================

def calculate_dimension7_v2(row: pd.Series, percentiles: Dict) -> Dict:
    """
    Calculate complete D7 v2.0 Phase 1A score.
    
    Components:
    1. Trading Activity (40%)
    2. Volatility Adjustment (10%)
    3. Market Recognition (50%)
    
    Args:
        row: Stock data row
        percentiles: Percentile thresholds
    
    Returns:
        Dictionary with all scores and metadata
    """
    # Calculate components
    c1 = calculate_trading_activity(row, percentiles)
    c2 = calculate_volatility_adjustment(row, percentiles)
    c3 = calculate_market_recognition(row)
    
    # Weighted composite
    composite_score = (
        c1['component_score'] * WEIGHTS['trading_activity'] +
        c2['component_score'] * WEIGHTS['volatility_adjustment'] +
        c3['component_score'] * WEIGHTS['market_recognition']
    )
    
    # Round to 1 decimal
    composite_score = round(composite_score, 1)
    
    return {
        'symbol': row['symbol'],
        'dimension7_v2_score': composite_score,
        
        # Component scores
        'component1_trading_activity': round(c1['component_score'], 1),
        'component2_volatility_adj': round(c2['component_score'], 1),
        'component3_market_recognition': round(c3['component_score'], 1),
        
        # Detailed metrics
        'trade_volume_score': round(c1['trade_volume_score'], 1),
        'share_volume_score': round(c1['share_volume_score'], 1),
        'trade_density_class': c1['trade_density_class'],
        'volatility_level': c2['volatility_level'],
        
        # Metadata
        'phase': '1A',
        'metrics_available': 4,
        'scoring_date': datetime.now().strftime('%Y-%m-%d')
    }

# =============================================================================
# MAIN SCORING FUNCTION
# =============================================================================

def score_stocks(cse_metrics_file: str, output_file: str, report_file: Optional[str] = None):
    """
    Score all stocks using D7 v2.0 Phase 1A methodology.
    
    Args:
        cse_metrics_file: Input CSV with CSE metrics
        output_file: Output CSV for scores
        report_file: Optional output TXT for report
    """
    print("="*80)
    print("DIMENSION 7 SCORER V2.0 - PHASE 1A")
    print("="*80)
    
    # Load percentiles
    percentiles = load_percentiles()
    
    # Load CSE metrics
    print(f"\n📊 Loading CSE metrics: {cse_metrics_file}")
    df = pd.read_csv(cse_metrics_file)
    print(f"   Stocks: {len(df):,}")
    
    # Score each stock
    print("\n🔢 Calculating D7 v2.0 Phase 1A scores...")
    results = []
    
    for idx, row in df.iterrows():
        score_data = calculate_dimension7_v2(row, percentiles)
        results.append(score_data)
        
        if (idx + 1) % 50 == 0:
            print(f"   Processed {idx + 1}/{len(df)} stocks...")
    
    # Convert to DataFrame
    scores_df = pd.DataFrame(results)
    
    # Sort by score (descending)
    scores_df = scores_df.sort_values('dimension7_v2_score', ascending=False).reset_index(drop=True)
    
    # Add rank
    scores_df.insert(1, 'rank', range(1, len(scores_df) + 1))
    
    # Save scores
    scores_df.to_csv(output_file, index=False)
    print(f"\n💾 Scores saved: {output_file}")
    
    # Generate report
    if report_file:
        generate_report(scores_df, percentiles, report_file)
    
    # Print summary
    print_summary(scores_df)
    
    print("\n" + "="*80)
    print("✅ D7 V2.0 PHASE 1A SCORING COMPLETE")
    print("="*80)

# =============================================================================
# REPORTING
# =============================================================================

def print_summary(scores_df: pd.DataFrame):
    """Print scoring summary."""
    
    print("\n📊 SCORING SUMMARY:")
    print(f"   Total Stocks: {len(scores_df):,}")
    print(f"   Mean Score: {scores_df['dimension7_v2_score'].mean():.1f}")
    print(f"   Median Score: {scores_df['dimension7_v2_score'].median():.1f}")
    print(f"   Std Dev: {scores_df['dimension7_v2_score'].std():.1f}")
    print(f"   Range: {scores_df['dimension7_v2_score'].min():.1f} - {scores_df['dimension7_v2_score'].max():.1f}")
    
    print("\n🏆 TOP 10 STOCKS:")
    top10 = scores_df.head(10)[['rank', 'symbol', 'dimension7_v2_score', 'trade_density_class', 'volatility_level']]
    print(top10.to_string(index=False))
    
    print("\n🎯 TEST STOCKS:")
    test_stocks = ['CTC.N0000', 'LION.N0000', 'LOFC.N0000', 'LOLC.N0000', 'JKH.N0000']
    test_df = scores_df[scores_df['symbol'].isin(test_stocks)][
        ['rank', 'symbol', 'dimension7_v2_score', 'component1_trading_activity', 
         'component2_volatility_adj', 'component3_market_recognition']
    ]
    if not test_df.empty:
        print(test_df.to_string(index=False))
    
    print("\n📊 TRADE DENSITY DISTRIBUTION:")
    density_counts = scores_df['trade_density_class'].value_counts()
    for density, count in density_counts.items():
        pct = (count / len(scores_df)) * 100
        print(f"   {density.capitalize():15s}: {count:3d} stocks ({pct:5.1f}%)")

def generate_report(scores_df: pd.DataFrame, percentiles: Dict, output_file: str):
    """Generate detailed scoring report."""
    
    report_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    report = f"""
{'='*80}
DIMENSION 7 V2.0 PHASE 1A SCORING REPORT
{'='*80}

Generated: {report_date}
Stocks Scored: {len(scores_df):,}
Phase: 1A (Initial CSE Enhancement)
Metrics Used: 4 (trade_volume, share_volume, intraday_volatility, trade_density)

{'='*80}
COMPONENT WEIGHTS
{'='*80}

Component 1 - Trading Activity:      40%
  • Trade Volume score (50% of component)
  • Share Volume score (50% of component)
  • Trade Density classification (informational)

Component 2 - Volatility Adjustment: 10%
  • Very stable (<2.2%): +10 bonus
  • Stable (2.2-3.5%): +5 bonus
  • Moderate (3.5-5.6%): Neutral
  • High (5.6-8.4%): -5 penalty
  • Very high (>8.4%): -10 penalty

Component 3 - Market Recognition:    50%
  • Uses v1.0 methodology (analyst data)
  • Placeholder: 50 (neutral) if no data

{'='*80}
SCORING DISTRIBUTION
{'='*80}

Mean:    {scores_df['dimension7_v2_score'].mean():6.1f}
Median:  {scores_df['dimension7_v2_score'].median():6.1f}
Std Dev: {scores_df['dimension7_v2_score'].std():6.1f}
Min:     {scores_df['dimension7_v2_score'].min():6.1f}
Max:     {scores_df['dimension7_v2_score'].max():6.1f}

Percentiles:
  90th: {scores_df['dimension7_v2_score'].quantile(0.90):6.1f}
  75th: {scores_df['dimension7_v2_score'].quantile(0.75):6.1f}
  50th: {scores_df['dimension7_v2_score'].quantile(0.50):6.1f}
  25th: {scores_df['dimension7_v2_score'].quantile(0.25):6.1f}
  10th: {scores_df['dimension7_v2_score'].quantile(0.10):6.1f}

{'='*80}
TOP 20 STOCKS
{'='*80}

"""
    
    top20 = scores_df.head(20)
    for _, row in top20.iterrows():
        report += f"\n{row['rank']:2d}. {row['symbol']:12s} Score: {row['dimension7_v2_score']:5.1f}\n"
        report += f"    Trading Activity: {row['component1_trading_activity']:5.1f} | "
        report += f"Volatility Adj: {row['component2_volatility_adj']:5.1f} | "
        report += f"Recognition: {row['component3_market_recognition']:5.1f}\n"
        report += f"    Density: {row['trade_density_class']:13s} | "
        report += f"Volatility: {row['volatility_level']}\n"
    
    report += f"""
{'='*80}
TRADE DENSITY ANALYSIS
{'='*80}

"""
    
    density_counts = scores_df['trade_density_class'].value_counts()
    for density, count in density_counts.items():
        pct = (count / len(scores_df)) * 100
        report += f"{density.capitalize():15s}: {count:3d} stocks ({pct:5.1f}%)\n"
    
    report += f"""
{'='*80}
NEXT STEPS
{'='*80}

1. Compare v2.0 Phase 1A scores to v1.0 baseline
2. Validate on test stocks (CTC, LION, LOFC, LOLC, JKH)
3. Deploy parallel scoring (v1.0 production, v2.0 validation)
4. Wait for Phase 1B-C data (20D metrics - Feb 3)
5. Full Phase 1D deployment (60D metrics - April 8)

{'='*80}
END OF REPORT
{'='*80}
"""
    
    with open(output_file, 'w') as f:
        f.write(report)
    
    print(f"📄 Report saved: {output_file}")

# =============================================================================
# CLI INTERFACE
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Dimension 7 v2.0 Phase 1A Scorer",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        '--input',
        type=str,
        default='cse_metrics.csv',
        help='Input CSV with CSE metrics'
    )
    
    parser.add_argument(
        '--output',
        type=str,
        default='dimension7_v2_scores.csv',
        help='Output CSV for scores'
    )
    
    parser.add_argument(
        '--report',
        type=str,
        default='dimension7_v2_report.txt',
        help='Output TXT for report'
    )
    
    args = parser.parse_args()
    
    score_stocks(args.input, args.output, args.report)
