
#!/usr/bin/env python3
"""
DIMENSION 7 SCORER V2.0 - PHASE 1B-D (FULL)
Investment OS - Market Sentiment Enhancement

FILE: dimension7_scorer_v2_0_phase1bcd.py
CREATED: 2026-02-15
AUTHOR: Investment OS

VERSION HISTORY:
    v2.0.0-1bcd  2026-02-15  Initial creation — Full 5-component scorer (Phase 1B-D)
    v2.0.1-1bcd  2026-02-16  Added version history header (new project standard)

Complete 5-Component Scorer

PURPOSE:
Enhanced market sentiment scoring using real CSE exchange data.
All 5 components active — data-gating constraints removed (OHLCV since 2010).
Runs in parallel with v1.0 for validation before migration.

PHASE 1B-D CAPABILITIES (Feb 2026):
✅ Component 1: Trading Activity (30%) - ENHANCED with CSE data
✅ Component 2: Volatility Adjustment (10%) - Fair comparison
✅ Component 3: Market Recognition (25%) - From v1.0
✅ Component 4: Volume Trends (10%) - NEW: 5D/20D accumulation signal
✅ Component 5: Multi-Timeframe Momentum (25%) - NEW: 5D/20D/60D returns

WEIGHT EVOLUTION:
Phase 1A:  Activity 40% | Volatility 10% | Recognition 50% | — | —
Phase 1BD: Activity 30% | Volatility 10% | Recognition 25% | Volume 10% | Momentum 25%

SCORING METHODOLOGY:
- Uses empirical CSE percentiles (no arbitrary thresholds)
- All scoring bands from cse_percentiles.json
- Multi-timeframe momentum with sub-weights: 5D(30%) + 20D(40%) + 60D(30%)
- Volume trends detect accumulation vs distribution
- Parallel deployment: v1.0 production unchanged

VERSION: 2.0-phase1bcd
DATE: February 15, 2026
AUTHOR: Investment OS Team
"""

import pandas as pd
import numpy as np
import json
from datetime import datetime
from typing import Dict, Optional
import argparse
import sys

# =============================================================================
# CONFIGURATION
# =============================================================================

# Percentiles file (generated by cse_percentile_calculator.py)
PERCENTILES_FILE = 'cse_percentiles.json'

# Component weights (Phase 1B-D — all 5 active)
WEIGHTS = {
    'trading_activity': 0.30,           # Enhanced with CSE data (was 0.40)
    'volatility_adjustment': 0.10,      # Fair comparison (unchanged)
    'market_recognition': 0.25,         # From v1.0 (was 0.50)
    'volume_trends': 0.10,              # NEW — accumulation/distribution
    'multi_timeframe_momentum': 0.25    # NEW — 5D/20D/60D price returns
}

# Momentum sub-weights (within Component 5)
MOMENTUM_SUB_WEIGHTS = {
    '5d': 0.30,    # Short-term: recent catalysts, earnings reactions
    '20d': 0.40,   # Medium-term: most actionable, filters noise
    '60d': 0.30    # Long-term: sustained trends, avoids mean-reversion traps
}

# =============================================================================
# LOAD PERCENTILES
# =============================================================================

def load_percentiles(filepath: str = PERCENTILES_FILE) -> Dict:
    """
    Load CSE percentile thresholds.

    Args:
        filepath: Path to percentiles JSON

    Returns:
        Dictionary with percentile data
    """
    try:
        with open(filepath, 'r') as f:
            percentiles = json.load(f)

        phase = percentiles.get('phase', 'unknown')
        metrics_count = percentiles.get('metrics_count', len(percentiles.get('metrics', {})))

        print(f"✅ Loaded percentiles: {filepath}")
        print(f"   Phase: {phase}")
        print(f"   Generated: {percentiles.get('generated_at', 'unknown')}")
        print(f"   Stocks: {percentiles.get('stocks_analyzed', 'unknown')}")
        print(f"   Metrics: {metrics_count}")

        # Validate required metrics for Phase 1B-D
        required = ['trade_volume', 'share_volume', 'intraday_volatility']
        phase1bd_metrics = ['volume_ratio_5d_20d', 'momentum_5d', 'momentum_20d', 'momentum_60d']

        for metric in required:
            if metric not in percentiles['metrics']:
                print(f"❌ ERROR: Required metric '{metric}' not found in percentiles")
                sys.exit(1)

        missing_new = [m for m in phase1bd_metrics if m not in percentiles['metrics']]
        if missing_new:
            print(f"⚠️  WARNING: Phase 1B-D metrics missing: {missing_new}")
            print(f"   Scorer will use neutral scores (50) for missing components")
            print(f"   Run: python3 cse_percentile_calculator.py cse_metrics.csv")

        return percentiles

    except FileNotFoundError:
        print(f"❌ ERROR: Percentiles file not found: {filepath}")
        print("   Run: python3 cse_percentile_calculator.py cse_metrics.csv")
        sys.exit(1)
    except Exception as e:
        print(f"❌ ERROR loading percentiles: {e}")
        sys.exit(1)

# =============================================================================
# SCORING FUNCTIONS
# =============================================================================

def score_by_percentile(value: float, bands: Dict, direction: str = 'higher_better') -> float:
    """
    Score a value using percentile bands.

    Args:
        value: Value to score
        bands: Scoring bands from percentiles
        direction: 'higher_better' or 'lower_better'

    Returns:
        Score (0-100)
    """
    if pd.isna(value):
        return 50.0  # Neutral score for missing data

    # Get band thresholds
    if direction == 'higher_better':
        if value >= bands['exceptional']['min']:
            return 95.0
        elif value >= bands['strong']['min']:
            return 82.0
        elif value >= bands['moderate']['min']:
            return 62.0
        elif value >= bands['weak']['min']:
            return 37.0
        else:
            return 12.0

    elif direction == 'lower_better':
        if value <= bands['exceptional']['max']:
            return 95.0
        elif value <= bands['strong']['max']:
            return 82.0
        elif value <= bands['moderate']['max']:
            return 62.0
        elif value <= bands['weak']['max']:
            return 37.0
        else:
            return 12.0

    return 50.0  # Default neutral

# =============================================================================
# COMPONENT 1: TRADING ACTIVITY (30%)
# =============================================================================

def calculate_trading_activity(row: pd.Series, percentiles: Dict) -> Dict:
    """
    Component 1: Trading Activity (30% weight)

    Uses:
    - Trade Volume (50% of component)
    - Share Volume (50% of component)
    - Trade Density (informational — not scored directly)

    Args:
        row: Stock data row
        percentiles: Percentile thresholds

    Returns:
        Dictionary with component scores and details
    """
    # Get percentile bands
    tv_bands = percentiles['metrics']['trade_volume']['scoring_bands']
    sv_bands = percentiles['metrics']['share_volume']['scoring_bands']

    # Score trade volume
    trade_volume_score = score_by_percentile(
        row.get('trade_volume', np.nan),
        tv_bands,
        'higher_better'
    )

    # Score share volume
    share_volume_score = score_by_percentile(
        row.get('share_volume', np.nan),
        sv_bands,
        'higher_better'
    )

    # Combined activity score (50/50 weight)
    activity_score = (trade_volume_score * 0.5) + (share_volume_score * 0.5)

    # Trade density classification (informational)
    trade_density = row.get('trade_density', np.nan)
    if pd.notna(trade_density):
        if trade_density >= 10000:
            density_class = 'institutional'
        elif trade_density >= 1000:
            density_class = 'mixed'
        else:
            density_class = 'retail'
    else:
        density_class = 'unknown'

    return {
        'component_score': activity_score,
        'trade_volume_score': trade_volume_score,
        'share_volume_score': share_volume_score,
        'trade_density_class': density_class
    }

# =============================================================================
# COMPONENT 2: VOLATILITY ADJUSTMENT (10%)
# =============================================================================

def calculate_volatility_adjustment(row: pd.Series, percentiles: Dict) -> Dict:
    """
    Component 2: Volatility Adjustment (10% weight)

    Purpose: Fair comparison across volatility profiles
    - Very stable stocks (low vol): Slight bonus
    - Very volatile stocks (high vol): Slight penalty
    - Most stocks: Neutral

    Args:
        row: Stock data row
        percentiles: Percentile thresholds

    Returns:
        Dictionary with adjustment score
    """
    volatility = row.get('intraday_volatility', np.nan)

    if pd.isna(volatility):
        return {'component_score': 50.0, 'volatility_level': 'unknown'}

    # Get percentile bands
    vol_bands = percentiles['metrics']['intraday_volatility']['scoring_bands']

    # Classification
    if volatility >= vol_bands['very_high']['min']:
        return {'component_score': 40.0, 'volatility_level': 'very_high'}
    elif volatility >= vol_bands['high']['min']:
        return {'component_score': 45.0, 'volatility_level': 'high'}
    elif volatility <= vol_bands['very_low']['max']:
        return {'component_score': 60.0, 'volatility_level': 'very_low'}
    elif volatility <= vol_bands['low']['max']:
        return {'component_score': 55.0, 'volatility_level': 'low'}
    else:
        return {'component_score': 50.0, 'volatility_level': 'moderate'}

# =============================================================================
# COMPONENT 3: MARKET RECOGNITION (25%)
# =============================================================================

def calculate_market_recognition(row: pd.Series) -> Dict:
    """
    Component 3: Market Recognition (25% weight)

    Uses v1.0 methodology (StockAnalysis.com data):
    - Analyst recommendations and total return metrics
    - Falls back to neutral (50) if no analyst data available

    Note: Weight reduced from 50% (Phase 1A) to 25% (Phase 1B-D)
    because momentum data now provides a more direct market signal.

    Args:
        row: Stock data row

    Returns:
        Dictionary with component score
    """
    if 'analyst_score' in row.index and pd.notna(row.get('analyst_score')):
        score = row['analyst_score']
    else:
        score = 50.0

    return {
        'component_score': score,
        'data_source': 'v1.0_analyst_data'
    }

# =============================================================================
# COMPONENT 4: VOLUME TRENDS (10%) — NEW
# =============================================================================

def calculate_volume_trends(row: pd.Series, percentiles: Dict) -> Dict:
    """
    Component 4: Volume Trends (10% weight)

    Purpose: Detect accumulation vs distribution using volume momentum.
    - 5D/20D volume ratio > 1: Recent volume above average (accumulation)
    - 5D/20D volume ratio < 1: Recent volume below average (distribution)

    Why it matters: Volume precedes price. Rising volume with flat price
    signals building pressure (institutional accumulation).

    Args:
        row: Stock data row
        percentiles: Percentile thresholds

    Returns:
        Dictionary with volume trend score and classification
    """
    volume_ratio = row.get('volume_ratio_5d_20d', np.nan)

    if pd.isna(volume_ratio):
        return {
            'component_score': 50.0,
            'volume_trend': 'unknown',
            'volume_ratio': None
        }

    # Check if we have percentile bands for this metric
    if 'volume_ratio_5d_20d' in percentiles['metrics']:
        vr_bands = percentiles['metrics']['volume_ratio_5d_20d']['scoring_bands']
        trend_score = score_by_percentile(volume_ratio, vr_bands, 'higher_better')
    else:
        # Fallback: hardcoded bands if percentiles not yet generated
        if volume_ratio >= 2.0:
            trend_score = 95.0
        elif volume_ratio >= 1.3:
            trend_score = 82.0
        elif volume_ratio >= 0.8:
            trend_score = 62.0
        elif volume_ratio >= 0.5:
            trend_score = 37.0
        else:
            trend_score = 12.0

    # Classify trend
    if volume_ratio >= 1.5:
        trend_class = 'strong_accumulation'
    elif volume_ratio >= 1.1:
        trend_class = 'mild_accumulation'
    elif volume_ratio >= 0.9:
        trend_class = 'neutral'
    elif volume_ratio >= 0.6:
        trend_class = 'mild_distribution'
    else:
        trend_class = 'strong_distribution'

    return {
        'component_score': trend_score,
        'volume_trend': trend_class,
        'volume_ratio': round(float(volume_ratio), 3)
    }

# =============================================================================
# COMPONENT 5: MULTI-TIMEFRAME MOMENTUM (25%) — NEW
# =============================================================================

def calculate_multi_timeframe_momentum(row: pd.Series, percentiles: Dict) -> Dict:
    """
    Component 5: Multi-Timeframe Momentum (25% weight)

    Uses three timeframes with sub-weights:
    - 5D return (30%): Recent catalysts, earnings reactions
    - 20D return (40%): Most actionable, filters noise
    - 60D return (30%): Sustained trends, avoids mean-reversion traps

    Multi-timeframe confluence logic:
    - All positive = Trend confirmation (highest conviction)
    - Mixed signals = Scored by sub-weighted average (natural dampening)
    - All negative = Sustained downtrend (lowest sentiment)

    Args:
        row: Stock data row
        percentiles: Percentile thresholds

    Returns:
        Dictionary with momentum scores and confluence assessment
    """
    momentum_5d = row.get('momentum_5d', np.nan)
    momentum_20d = row.get('momentum_20d', np.nan)
    momentum_60d = row.get('momentum_60d', np.nan)

    scores = {}
    timeframes = {
        '5d': momentum_5d,
        '20d': momentum_20d,
        '60d': momentum_60d
    }

    for tf, value in timeframes.items():
        metric_key = f'momentum_{tf}'
        if pd.isna(value):
            scores[tf] = 50.0  # Neutral for missing
        elif metric_key in percentiles['metrics']:
            bands = percentiles['metrics'][metric_key]['scoring_bands']
            scores[tf] = score_by_percentile(value, bands, 'higher_better')
        else:
            # Fallback: simple scoring if percentiles not yet generated
            if value >= 10.0:
                scores[tf] = 95.0
            elif value >= 3.0:
                scores[tf] = 82.0
            elif value >= 0.0:
                scores[tf] = 62.0
            elif value >= -5.0:
                scores[tf] = 37.0
            else:
                scores[tf] = 12.0

    # Sub-weighted composite
    momentum_score = (
        scores['5d'] * MOMENTUM_SUB_WEIGHTS['5d'] +
        scores['20d'] * MOMENTUM_SUB_WEIGHTS['20d'] +
        scores['60d'] * MOMENTUM_SUB_WEIGHTS['60d']
    )

    # Confluence assessment
    directions = []
    for tf, value in timeframes.items():
        if pd.notna(value):
            directions.append('positive' if value > 0 else 'negative' if value < 0 else 'flat')

    if all(d == 'positive' for d in directions):
        confluence = 'full_uptrend'
    elif all(d == 'negative' for d in directions):
        confluence = 'full_downtrend'
    elif len(directions) >= 2 and directions.count('positive') > directions.count('negative'):
        confluence = 'mostly_positive'
    elif len(directions) >= 2 and directions.count('negative') > directions.count('positive'):
        confluence = 'mostly_negative'
    else:
        confluence = 'mixed'

    return {
        'component_score': momentum_score,
        'momentum_5d_score': scores['5d'],
        'momentum_20d_score': scores['20d'],
        'momentum_60d_score': scores['60d'],
        'momentum_5d_pct': round(float(momentum_5d), 2) if pd.notna(momentum_5d) else None,
        'momentum_20d_pct': round(float(momentum_20d), 2) if pd.notna(momentum_20d) else None,
        'momentum_60d_pct': round(float(momentum_60d), 2) if pd.notna(momentum_60d) else None,
        'confluence': confluence
    }

# =============================================================================
# COMPOSITE SCORING
# =============================================================================

def calculate_dimension7_v2(row: pd.Series, percentiles: Dict) -> Dict:
    """
    Calculate complete D7 v2.0 Phase 1B-D score.

    Components:
    1. Trading Activity (30%)
    2. Volatility Adjustment (10%)
    3. Market Recognition (25%)
    4. Volume Trends (10%)
    5. Multi-Timeframe Momentum (25%)

    Args:
        row: Stock data row
        percentiles: Percentile thresholds

    Returns:
        Dictionary with all scores and metadata
    """
    # Calculate all 5 components
    c1 = calculate_trading_activity(row, percentiles)
    c2 = calculate_volatility_adjustment(row, percentiles)
    c3 = calculate_market_recognition(row)
    c4 = calculate_volume_trends(row, percentiles)
    c5 = calculate_multi_timeframe_momentum(row, percentiles)

    # Weighted composite
    composite_score = (
        c1['component_score'] * WEIGHTS['trading_activity'] +
        c2['component_score'] * WEIGHTS['volatility_adjustment'] +
        c3['component_score'] * WEIGHTS['market_recognition'] +
        c4['component_score'] * WEIGHTS['volume_trends'] +
        c5['component_score'] * WEIGHTS['multi_timeframe_momentum']
    )

    # Round to 1 decimal
    composite_score = round(composite_score, 1)

    return {
        'symbol': row.get('symbol', 'UNKNOWN'),
        'dimension7_v2_score': composite_score,

        # Component scores
        'c1_trading_activity': round(c1['component_score'], 1),
        'c2_volatility_adj': round(c2['component_score'], 1),
        'c3_market_recognition': round(c3['component_score'], 1),
        'c4_volume_trends': round(c4['component_score'], 1),
        'c5_momentum': round(c5['component_score'], 1),

        # Detailed metrics
        'trade_volume_score': round(c1['trade_volume_score'], 1),
        'share_volume_score': round(c1['share_volume_score'], 1),
        'trade_density_class': c1['trade_density_class'],
        'volatility_level': c2['volatility_level'],
        'volume_trend': c4['volume_trend'],
        'volume_ratio': c4['volume_ratio'],
        'momentum_confluence': c5['confluence'],
        'momentum_5d_pct': c5['momentum_5d_pct'],
        'momentum_20d_pct': c5['momentum_20d_pct'],
        'momentum_60d_pct': c5['momentum_60d_pct'],
        'momentum_5d_score': round(c5['momentum_5d_score'], 1),
        'momentum_20d_score': round(c5['momentum_20d_score'], 1),
        'momentum_60d_score': round(c5['momentum_60d_score'], 1),

        # Metadata
        'phase': '1B-D',
        'components_active': 5,
        'metrics_available': 10,
        'scoring_date': datetime.now().strftime('%Y-%m-%d')
    }

# =============================================================================
# MAIN SCORING FUNCTION
# =============================================================================

def score_stocks(cse_metrics_file: str, output_file: str, report_file: Optional[str] = None):
    """
    Score all stocks using D7 v2.0 Phase 1B-D methodology.

    Args:
        cse_metrics_file: Input CSV with CSE metrics
        output_file: Output CSV for scores
        report_file: Optional output TXT for report
    """
    print("=" * 80)
    print("DIMENSION 7 SCORER V2.0 - PHASE 1B-D (FULL)")
    print("=" * 80)

    # Load percentiles
    percentiles = load_percentiles()

    # Load CSE metrics
    print(f"\n📊 Loading CSE metrics: {cse_metrics_file}")
    df = pd.read_csv(cse_metrics_file)
    print(f"   Stocks: {len(df):,}")
    print(f"   Columns: {', '.join(df.columns.tolist())}")

    # Verify required columns
    required_cols = ['symbol', 'trade_volume', 'share_volume', 'intraday_volatility']
    phase1bd_cols = ['volume_ratio_5d_20d', 'momentum_5d', 'momentum_20d', 'momentum_60d']

    missing_required = [c for c in required_cols if c not in df.columns]
    if missing_required:
        print(f"❌ ERROR: Missing required columns: {missing_required}")
        sys.exit(1)

    missing_new = [c for c in phase1bd_cols if c not in df.columns]
    if missing_new:
        print(f"⚠️  WARNING: Phase 1B-D columns missing: {missing_new}")
        print(f"   Components 4-5 will use neutral scores (50)")

    # Score each stock
    print(f"\n🔢 Calculating D7 v2.0 Phase 1B-D scores ({len(df)} stocks)...")
    print(f"   Weights: Activity={WEIGHTS['trading_activity']:.0%} | "
          f"Volatility={WEIGHTS['volatility_adjustment']:.0%} | "
          f"Recognition={WEIGHTS['market_recognition']:.0%} | "
          f"Volume={WEIGHTS['volume_trends']:.0%} | "
          f"Momentum={WEIGHTS['multi_timeframe_momentum']:.0%}")

    results = []

    for idx, row in df.iterrows():
        score_data = calculate_dimension7_v2(row, percentiles)
        results.append(score_data)

        if (idx + 1) % 50 == 0:
            print(f"   Processed {idx + 1}/{len(df)} stocks...")

    # Convert to DataFrame
    scores_df = pd.DataFrame(results)

    # Sort by score (descending)
    scores_df = scores_df.sort_values('dimension7_v2_score', ascending=False).reset_index(drop=True)

    # Add rank
    scores_df.insert(1, 'rank', range(1, len(scores_df) + 1))

    # Save scores
    scores_df.to_csv(output_file, index=False)
    print(f"\n💾 Scores saved: {output_file}")

    # Generate report
    if report_file:
        generate_report(scores_df, percentiles, report_file)

    # Print summary
    print_summary(scores_df)

    print("\n" + "=" * 80)
    print("✅ D7 V2.0 PHASE 1B-D SCORING COMPLETE")
    print("=" * 80)

# =============================================================================
# REPORTING
# =============================================================================

def print_summary(scores_df: pd.DataFrame):
    """Print scoring summary."""

    print("\n📊 SCORING SUMMARY:")
    print(f"   Total Stocks: {len(scores_df):,}")
    print(f"   Mean Score: {scores_df['dimension7_v2_score'].mean():.1f}")
    print(f"   Median Score: {scores_df['dimension7_v2_score'].median():.1f}")
    print(f"   Std Dev: {scores_df['dimension7_v2_score'].std():.1f}")
    print(f"   Range: {scores_df['dimension7_v2_score'].min():.1f} - "
          f"{scores_df['dimension7_v2_score'].max():.1f}")

    print("\n🏆 TOP 10 STOCKS:")
    top10 = scores_df.head(10)[[
        'rank', 'symbol', 'dimension7_v2_score',
        'c1_trading_activity', 'c4_volume_trends', 'c5_momentum',
        'momentum_confluence', 'trade_density_class'
    ]]
    print(top10.to_string(index=False))

    print("\n🎯 TEST STOCKS:")
    test_stocks = ['CTC.N0000', 'LION.N0000', 'LOFC.N0000', 'LOLC.N0000', 'JKH.N0000']
    test_df = scores_df[scores_df['symbol'].isin(test_stocks)][[
        'rank', 'symbol', 'dimension7_v2_score',
        'c1_trading_activity', 'c2_volatility_adj', 'c3_market_recognition',
        'c4_volume_trends', 'c5_momentum'
    ]]
    if not test_df.empty:
        print(test_df.to_string(index=False))

    print("\n📈 MOMENTUM CONFLUENCE DISTRIBUTION:")
    if 'momentum_confluence' in scores_df.columns:
        confluence_counts = scores_df['momentum_confluence'].value_counts()
        for conf, count in confluence_counts.items():
            pct = (count / len(scores_df)) * 100
            print(f"   {conf:20s}: {count:3d} stocks ({pct:5.1f}%)")

    print("\n📊 TRADE DENSITY DISTRIBUTION:")
    density_counts = scores_df['trade_density_class'].value_counts()
    for density, count in density_counts.items():
        pct = (count / len(scores_df)) * 100
        print(f"   {density.capitalize():15s}: {count:3d} stocks ({pct:5.1f}%)")

    print("\n📊 VOLUME TREND DISTRIBUTION:")
    if 'volume_trend' in scores_df.columns:
        trend_counts = scores_df['volume_trend'].value_counts()
        for trend, count in trend_counts.items():
            pct = (count / len(scores_df)) * 100
            print(f"   {trend:25s}: {count:3d} stocks ({pct:5.1f}%)")


def generate_report(scores_df: pd.DataFrame, percentiles: Dict, output_file: str):
    """Generate detailed scoring report."""

    report_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    report = f"""
{'=' * 80}
DIMENSION 7 V2.0 PHASE 1B-D SCORING REPORT (FULL 5-COMPONENT)
{'=' * 80}

Generated: {report_date}
Stocks Scored: {len(scores_df):,}
Phase: 1B-D (All 5 Components Active)
Metrics Used: 10
Components: 5

{'=' * 80}
COMPONENT WEIGHTS
{'=' * 80}

Component 1 - Trading Activity:         30% (was 40% in Phase 1A)
  * Trade Volume score (50% of component)
  * Share Volume score (50% of component)
  * Trade Density classification (informational)

Component 2 - Volatility Adjustment:    10% (unchanged)
  * Very stable: +10 bonus
  * Stable: +5 bonus
  * Moderate: Neutral
  * High: -5 penalty
  * Very high: -10 penalty

Component 3 - Market Recognition:       25% (was 50% in Phase 1A)
  * Uses v1.0 methodology (analyst data)
  * Placeholder: 50 (neutral) if no data

Component 4 - Volume Trends:            10% (NEW)
  * 5D/20D volume ratio (accumulation/distribution)
  * Higher = recent volume exceeds average = interest building

Component 5 - Multi-Timeframe Momentum: 25% (NEW)
  * 5D return (30% sub-weight): Recent catalysts
  * 20D return (40% sub-weight): Most actionable signal
  * 60D return (30% sub-weight): Sustained trends
  * Confluence assessment: all-positive to all-negative

Total: 30% + 10% + 25% + 10% + 25% = 100%

{'=' * 80}
SCORING DISTRIBUTION
{'=' * 80}

Mean:    {scores_df['dimension7_v2_score'].mean():6.1f}
Median:  {scores_df['dimension7_v2_score'].median():6.1f}
Std Dev: {scores_df['dimension7_v2_score'].std():6.1f}
Min:     {scores_df['dimension7_v2_score'].min():6.1f}
Max:     {scores_df['dimension7_v2_score'].max():6.1f}

Percentiles:
  90th: {scores_df['dimension7_v2_score'].quantile(0.90):6.1f}
  75th: {scores_df['dimension7_v2_score'].quantile(0.75):6.1f}
  50th: {scores_df['dimension7_v2_score'].quantile(0.50):6.1f}
  25th: {scores_df['dimension7_v2_score'].quantile(0.25):6.1f}
  10th: {scores_df['dimension7_v2_score'].quantile(0.10):6.1f}

{'=' * 80}
TOP 20 STOCKS
{'=' * 80}

"""

    top20 = scores_df.head(20)
    for _, row in top20.iterrows():
        report += f"\n{row['rank']:2d}. {row['symbol']:12s} Score: {row['dimension7_v2_score']:5.1f}\n"
        report += f"    Activity: {row['c1_trading_activity']:5.1f} | "
        report += f"Vol Adj: {row['c2_volatility_adj']:5.1f} | "
        report += f"Recognition: {row['c3_market_recognition']:5.1f} | "
        report += f"Vol Trend: {row['c4_volume_trends']:5.1f} | "
        report += f"Momentum: {row['c5_momentum']:5.1f}\n"
        report += f"    Density: {row['trade_density_class']:13s} | "
        report += f"Volatility: {row['volatility_level']:10s} | "
        report += f"Trend: {row['volume_trend']:20s} | "
        report += f"Confluence: {row['momentum_confluence']}\n"
        if row.get('momentum_5d_pct') is not None:
            report += f"    Momentum: 5D={row['momentum_5d_pct']:+.1f}% | "
            report += f"20D={row['momentum_20d_pct']:+.1f}% | "
            report += f"60D={row['momentum_60d_pct']:+.1f}%\n"

    report += f"""
{'=' * 80}
MOMENTUM CONFLUENCE ANALYSIS
{'=' * 80}

"""
    if 'momentum_confluence' in scores_df.columns:
        confluence_counts = scores_df['momentum_confluence'].value_counts()
        for conf, count in confluence_counts.items():
            pct = (count / len(scores_df)) * 100
            report += f"{conf:20s}: {count:3d} stocks ({pct:5.1f}%)\n"

    report += f"""
{'=' * 80}
VOLUME TREND ANALYSIS
{'=' * 80}

"""
    if 'volume_trend' in scores_df.columns:
        trend_counts = scores_df['volume_trend'].value_counts()
        for trend, count in trend_counts.items():
            pct = (count / len(scores_df)) * 100
            report += f"{trend:25s}: {count:3d} stocks ({pct:5.1f}%)\n"

    report += f"""
{'=' * 80}
COMPARISON NOTES
{'=' * 80}

Phase 1A had 3 components (4 metrics):
  Market Recognition dominated at 50% weight with neutral (50) placeholder.
  Effective scoring was driven by Trading Activity (40%).
  Score range was narrow (limited differentiation).

Phase 1B-D has 5 components (10 metrics):
  No single component dominates (max 30%).
  Momentum adds differentiation based on actual price trends.
  Volume trends detect accumulation/distribution early.
  Expect wider score range and better stock separation.

NEXT STEPS:
1. Compare Phase 1B-D to v1.0 baseline (compare_d7_versions.py)
2. Validate on test stocks (CTC, LION, LOFC, LOLC, JKH)
3. Run weekly for 4 weeks in parallel
4. Migration Decision: March 15, 2026

{'=' * 80}
END OF REPORT
{'=' * 80}
"""

    with open(output_file, 'w') as f:
        f.write(report)

    print(f"📄 Report saved: {output_file}")

# =============================================================================
# CLI INTERFACE
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Dimension 7 v2.0 Phase 1B-D Scorer (Full 5-Component)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Score using default files
  python3 dimension7_scorer_v2_0_phase1bcd.py

  # Specify custom input/output
  python3 dimension7_scorer_v2_0_phase1bcd.py \\
      --input cse_metrics.csv \\
      --output dimension7_v2_scores.csv \\
      --report dimension7_v2_report.txt
        """
    )

    parser.add_argument(
        '--input',
        type=str,
        default='cse_metrics.csv',
        help='Input CSV with CSE metrics'
    )

    parser.add_argument(
        '--output',
        type=str,
        default='dimension7_v2_scores.csv',
        help='Output CSV for scores'
    )

    parser.add_argument(
        '--report',
        type=str,
        default='dimension7_v2_report.txt',
        help='Output TXT for report'
    )

    args = parser.parse_args()

    score_stocks(args.input, args.output, args.report)
